name: Java CI with Maven

on:
  push:
    branches:
      - '**'  # This will match any branch
  pull_request:
    branches:
      - '**'  # This will match any branch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          INSTALL4J_LICENSE: ${{ secrets.INSTALL4J_LICENSE }}
