theme: jekyll-theme-leap-day
title: Lince PLUS
description: Lince plus is a multiplatform software for behaviour research based on java within a web context and an statistical flavour
show_downloads: false
google_analytics: UA-78568633-3
logo: /docs/lince-icon.pnghttps://albertosoto.github.io/lince-plus/
