name: Java CI with Maven

on:
  push:
    branches:
      - '**'  # This will match any branch
  pull_request:
    branches:
      - '**'  # This will match any branch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: cicd
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Download and setup Install4j
        run: | 
          wget https://download.ej-technologies.com/install4j/install4j_linux-x64_10_0_9.deb
          sudo dpkg -i install4j_linux-x64_10_0_9.deb
          echo "INSTALL4J_HOME=/opt/install4j10" >> $GITHUB_ENV

#  ==> Valid
#      - name: Verify Install4j
#        run: |
#          ls -l /opt/install4j10
#          which install4j || echo "install4j not found in PATH"
#          echo $INSTALL4J_HOME
#      - name: Print System Info
#        run: |
#          echo "Architecture: $(uname -m)"
#          echo "Operating System: $(uname -s)"
#          echo "OS Version: $(uname -r)"
#          lsb_release -a
#          dpkg --print-architecture
#      - name: Check Install4j Setup
#        run: |
#          echo "INSTALL4J_HOME: $INSTALL4J_HOME"
#          ls -l $INSTALL4J_HOME
#          ls -l $INSTALL4J_HOME/bin
#          file $INSTALL4J_HOME/bin/install4jc
#          $INSTALL4J_HOME/bin/install4jc --version
#          sudo ls -l /opt/install4j10
#          whoami
#          groups

      - name: Check INSTALL4J_LICENSE
        run: |
          if [ -n "$INSTALL4J_LICENSE" ]; then
            echo "INSTALL4J_LICENSE is set"
            echo "Full INSTALL4J_LICENSE value:"
            echo "$INSTALL4J_LICENSE"
            echo "Length: ${#INSTALL4J_LICENSE}"
          else
            echo "INSTALL4J_LICENSE is not set"
          fi
        env:
          INSTALL4J_LICENSE: ${{ secrets.INSTALL4J_LICENSE }}

#      - name: Use secret in script
#        env:
#          # Reference the secret using secrets context
#          API_KEY: ${{ secrets.API_KEY }}
#        run: |
#          # Example of using the secret in a script
#          echo "Using API key length: ${#API_KEY}"  # Print length only for security
#
      - name: Build with Maven
        run: |
          cd src
          mvn -B package install -DskipTests -DinstallDir="${INSTALL4J_HOME}" -Dinstall4j.licenseKey="${{ secrets.INSTALL4J_LICENSE_KEY }}"
        env:
          INSTALL4J_HOME: "/opt/install4j10"
          INSTALL4J_LICENSE: ${{ secrets.INSTALL4J_LICENSE }}

      - name: Display output.txt
        run: |
          if [ -f src/installer/output.txt ]; then
            echo "Contents of output.txt:"
            cat src/installer/output.txt
          else
            echo "output.txt file not found in src/installer/"
          fi

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f src/pom.xml)

      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: true
          prerelease: false

      - name: Configure Maven settings
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: '[{"id": "github", "username": "${GITHUB_ACTOR}", "password": "${GITHUB_TOKEN}"}]'

      - name: Deploy to GitHub Packages
        run: cd src && mvn deploy
#        run: mvn deploy -f src/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload DMG Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./src/installer/lince-${{ steps.get_version.outputs.VERSION }}.dmg
          asset_name: lince-${{ steps.get_version.outputs.VERSION }}.dmg
          asset_content_type: application/x-apple-diskimage

      - name: Upload EXE Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./src/installer/lince-${{ steps.get_version.outputs.VERSION }}.exe
          asset_name: lince-${{ steps.get_version.outputs.VERSION }}.exe
          asset_content_type: application/vnd.microsoft.portable-executable

#      - name: Upload Release Asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: ./target/*.jar
#          asset_name: lince-${{ steps.get_version.outputs.VERSION }}.jar
#          asset_content_type: application/java-archive
